# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: pyosim_aws
channels:
- conda-forge
- pyomeca
dependencies:
- python
- nb_conda_kernels
- pyyaml
- numpy
- lapack
- pandas
- pyomeca
#- pyosim
- pyoviz
- altair
- nb_black
- pip
- pip:
  - -e .
  - spm1d
